import type { Metadata } from "next";
import localFont from "next/font/local";
import {AppRouterCacheProvider} from '@mui/material-nextjs/v14-appRouter'
import MyThemeProvider from '@/app/components/MyThemeProvider'
import InitColorSchemeScript from '@mui/material/InitColorSchemeScript';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "NextJs Material UI 6",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html suppressHydrationWarning lang="en">
      <body style={{margin: 0, padding: 0}} className={`${geistSans.variable} ${geistMono.variable}`}>
      <InitColorSchemeScript attribute="class" />
      <AppRouterCacheProvider>
          <MyThemeProvider>
            {children}
          </MyThemeProvider>
      </AppRouterCacheProvider>
      </body>
    </html>
  );
}
